### ISSUE TITLE
POST Issue comment and PullRequest comment

### ISSUE THREAD

**Issue by HALU5071** [moatwel/rosetta#158]
# branch info
|branch from|branch working|merge to|
|:---:|:---:|:---:|
|dev/1.0.0|feature-158|dev/1.0.0|

POST issue comment

use `APIClient#postIssueComment()`

**Comment by HALU5071** [comment]
comment

**Comment by HALU5071** [comment]
comment2

**Comment by HALU5071** [comment]
comment

**Comment by HALU5071** [comment]
hello

**Comment by basilbasil50** [comment]
Goog Comments
